Repository Todotodot/todotodot-client, pull requests merged in 2022-06, with the labels that each got.

#7 design: Error view
  .husky/pre-commit
  package-lock.json
  src/assets/images/error/big-speech-bubble.png
  src/assets/images/error/bunny.png
  src/assets/images/error/dust.png
  src/assets/images/error/rino.png
  src/assets/images/error/small-speech-bubble.png
  src/assets/images/error/turtle.png
  src/components/Error/Error.js
Labels: 기능구현

#8 feat: Complete Confirmation, GameResult, TodoGroup modal
  public/index.html
  src/app/App.js
  src/components/Modal/ConfirmationModal.js
  src/components/Modal/GameResultModal.js
  src/components/Modal/Modal.js
  src/components/Modal/TodoGroupModal.js
  src/components/Portal/Portal.js
Labels: 기능구현

#9 feat: Implement Profile component with user data
  src/assets/images/search-icon.png
  src/components/Profile/Profile.js
  src/components/shared/Button.js
Labels: 기능구현

#10 feat: Implement Loading component
  src/components/Game/Loading.js
Labels: 기능구현

#12 feat: TodoList view and GroupList view
  src/assets/images/icons/exit.png
  src/assets/images/icons/pencil.png
  src/assets/images/icons/trash-can.png
  src/components/GroupList/GroupList.js
  src/components/TodoList/TodoList.js
  src/components/shared/Dropdown.js
  src/components/shared/Line.js
  src/components/shared/ListItemContainer.js
  src/components/shared/MainContainer.js
Labels: 기능구현

#11 feat: Implement user list component
  src/assets/images/back-button.png
  src/components/UserList/UserList.js
Labels: 기능구현

#15 feat: Implement game logic with Socket IO
  src/assets/images/inGameBackground.png
  src/components/Game/InGame.js
  src/components/Game/Loading.js
  src/components/TodoList/TodoList.js
  src/hooks/useTimeout.js
Labels: 디자인변경, 기능구현

#17 Feat/group
  src/api/index.js
  src/components/Group/Group.js
  src/components/GroupList/GroupList.js
  src/components/Main/Main.js
  src/components/Modal/ConfirmationModal.js
  src/components/Modal/GameResultModal.js
  src/components/Modal/TodoGroupModal.js
  src/components/Profile/Profile.js
  src/components/TodoList/TodoList.js
  src/components/UserList/UserList.js
  src/features/clickSlice.js
Labels: 버그수정, 리팩토링, 기능구현

#18 Feat/game
  src/app/App.js
  src/assets/images/characters/EarthWizard-attack.png
  src/components/Game/Game.js
  src/components/Modal/TodoGroupModal.js
  src/constants/charactersInfo.js
Labels: 기능구현

#21 feat: Add Personal game character rendering & fix rendering bug
  src/components/Game/Game.js
  src/components/Modal/TodoGroupModal.js
  src/utils/characterInfoList.js
Labels: 버그수정, 기능구현

#25 refactor: Change esLint and prettier settings
  .eslintrc.json
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/Game/Game.js
  src/components/Group/Group.js
  src/components/GroupList/GroupList.js
  src/components/Modal/ConfirmationModal.js
  src/components/Modal/GameResultModal.js
  src/components/Modal/TodoGroupModal.js
  src/components/Profile/Profile.js
  src/components/TodoList/TodoList.js
  src/components/UserList/UserList.js
  src/hooks/useTimeout.js
  src/setupTests.js
  src/utils/characterInfoList.js
  src/utils/todosFilter.js
Labels: 리팩토링

#26 test: Add Login test code
  src/components/Login/Login.test.js
Labels: 테스트코드

#28 docs: Update restropect
  README.md
Labels: 문서
